"""Convert flux_fluence.csv to a LaTeX table of time-integrated (T90) GBM fluences.

Adapted from codes-for-paper/amati_relationship/csv_to_latex.py (decimals_for,
format_value_with_errors, GRB_TEX_MACROS, format_grb_name/format_model_name are
copies of that script's helpers, per CLAUDE.md's cross-folder-import convention).
"""

import numpy as np
import pandas as pd

# Significant figures to preserve on the smallest error in a column.
ERROR_SIG_FIGS = 2

# Normalisation for the fluence column, carried in the table header.
FLUENCE_NORM = 1e-4


def decimals_for(errors, norm=1.0, sig=ERROR_SIG_FIGS, cap=6):
    """Decimal places such that the smallest error in a column keeps `sig` digits.

    Derived from the data rather than hardcoded, so the table cannot silently
    lose precision -- or print spurious precision -- if the inputs change.
    """
    values = np.asarray(errors, dtype=float) / norm
    values = values[np.isfinite(values) & (values > 0)]
    if values.size == 0:
        return 2
    return max(0, min(int(sig - 1 - np.floor(np.log10(values.min()))), cap))


def format_value_with_errors(value, err_lower, err_upper, decimals=3):
    """Format a value with asymmetric errors for LaTeX: $value_{-lower}^{+upper}$."""
    return f"${value:.{decimals}f}_{{-{err_lower:.{decimals}f}}}^{{+{err_upper:.{decimals}f}}}$"


def exponent_label(norm):
    """LaTeX for the power of ten a column is normalised by, e.g. 10^{-4}."""
    return f"10^{{{int(np.log10(norm))}}}"


# The paper defines a macro per burst (preamble.tex) so names stay consistent
# everywhere; emit those rather than literal text.
GRB_TEX_MACROS = {
    "GRB080916C": r"\grbzeroeightzeroninesixteenC",
    "GRB131014A": r"\grbthirteentenfourteenA",
    "GRB140206B": r"\grbfourteenzerotwozerosixB",
    "GRB231129C": r"\grbtwentythreeeleventwentynineC",
}


def format_grb_name(grb_name):
    """Format GRB name for LaTeX, using the paper's per-burst macro."""
    return GRB_TEX_MACROS.get(grb_name, grb_name)


def format_model_name(model_name):
    """Format model name for LaTeX, using the paper's per-model macro.

    The preamble defines one macro per model combination, named as the
    lower-cased model with separators removed: ``SBPL_BB`` -> ``\\sbplbb``.
    """
    return "\\" + model_name.lower().replace("_", "")


def csv_to_latex_table(csv_path="flux_fluence.csv", output_path="fluence_table.tex"):
    """Convert the time-integrated (T90) rows of flux_fluence.csv to a LaTeX table.

    Restricted to T90 -- one row per burst -- since this table exists to
    substantiate the "high GBM fluence" sample-selection criterion
    (section-1-introduction.tex), not to report every episode's fluence.
    """
    df = pd.read_csv(csv_path)
    df = df[df["ep_type"] == "T90"].reset_index(drop=True)

    e_min = df["e_min_keV"].iloc[0]
    e_max = df["e_max_keV"].iloc[0]
    n_samples = int(df["n_samples"].iloc[0])
    seed = int(df["seed"].iloc[0])

    fluence_decimals = decimals_for(
        np.r_[df["fluence_err_lower_erg_cm2"], df["fluence_err_upper_erg_cm2"]], norm=FLUENCE_NORM
    )

    latex_lines = [
        "% AUTO-GENERATED by codes-for-paper/fluence/csv_to_latex.py",
        "% Do not edit by hand — regenerate from flux_fluence.csv instead.",
        "\\begin{table}[!ht]",
        "    \\centering",
        (
            "    \\caption{Time-integrated (\\tnty) \\ac{GBM} bolometric fluence, substantiating "
            "the ``high fluence'' sample-selection criterion (\\cref{sec:introduction}).\n"
            f"        The fluence is integrated over the observed {e_min:.0f}~keV to "
            f"{e_max / 1e3:.0f}~MeV band from the best-fit spectral model of each burst's \\tnty\\ "
            "interval; being purely observer-frame, it does not depend on redshift or cosmology.\n"
            f"        Values are the median and asymmetric $1\\sigma$ errors from ${n_samples}$ "
            f"Monte Carlo samples (seed ${seed}$).}}"
        ),
        "    \\label{tab:fluence}",
        "    \\renewcommand{\\arraystretch}{1.25}",
        "    \\resizebox{\\columnwidth}{!}{",
        "    \\begin{tabular}{lcc}",
        "        \\toprule",
        "        \\ac{GRB} & Model & Fluence " + f"[${exponent_label(FLUENCE_NORM)}$ erg\\,cm$^{{-2}}$] \\\\",
        "        \\midrule",
    ]

    for _, row in df.iterrows():
        grb_display = format_grb_name(row["grb_name"])
        model_display = format_model_name(row["model_name"])
        fluence_str = format_value_with_errors(
            row["fluence_erg_cm2"] / FLUENCE_NORM,
            row["fluence_err_lower_erg_cm2"] / FLUENCE_NORM,
            row["fluence_err_upper_erg_cm2"] / FLUENCE_NORM,
            decimals=fluence_decimals,
        )
        latex_lines.append(f"        {grb_display} & {model_display} & {fluence_str} \\\\")

    latex_lines.append("        \\bottomrule")
    latex_lines.append("    \\end{tabular}\n}")
    latex_lines.append("\\end{table}")

    with open(output_path, "w") as f:
        f.write("\n".join(latex_lines))

    print(f"LaTeX table written to {output_path}")
    print(f"Total rows: {len(df)}")
    print("\n" + "=" * 80)
    for line in latex_lines:
        print(line)


if __name__ == "__main__":
    csv_to_latex_table()
