"""
Lorentz-factor LaTeX table generator (Limit B)
===============================================
Pure CSV-in, tex-out: reads ``lorentz_results_limit_b.csv`` (written by
``lorentz_factor_limit_b.py``) and renders ``lorentz_table_limit_b.tex``. Has no dependency
on ``grb_research``/``results.json`` and does not recompute anything, so it can be rerun on
its own -- e.g. to pick up a table-formatting change -- without repeating the Gamma_min_B
Monte Carlo.

``fmt``/``fmt_t_v``/``T_V_SOURCE_MARKER``/``TEX_NAMES`` are imported from
``generate_lorentz_table.py`` (Limit A's own generator) rather than duplicated -- they are
algebraically/textually identical between the two limits, and this project already treats
that kind of duplication as a drift risk (see ``lorentz_factor_limit_b.py``'s own docstring
on why it imports ``compute_tau_hat`` from ``lorentz_factor.py`` rather than re-deriving it).

Run standalone with ``python generate_lorentz_table_limit_b.py`` from this directory, or via
``lorentz_factor_limit_b.py``'s ``main()``, which shells out to this script by subprocess
after writing ``lorentz_results_limit_b.csv``.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from generate_lorentz_table import TEX_NAMES, episode_order, fmt, fmt_t_v

HERE = Path(__file__).parent
RESULTS_CSV = HERE / "lorentz_results_limit_b.csv"
TABLE_TEX = HERE / "lorentz_table_limit_b.tex"


def load_results(csv_path=RESULTS_CSV):
    """Read lorentz_results_limit_b.csv into the list-of-dicts shape build_latex_table() expects.

    pandas reads an empty/None cell back as NaN, not None -- fmt()/fmt_t_v() check `is None`,
    so NaN has to be converted back explicitly or every such cell would render as a stray
    number instead of the intended ``\\ldots``/bare-duration formatting.
    """
    df = pd.read_csv(csv_path)
    df["tex_name"] = df["GRB"].map(lambda g: TEX_NAMES[g.removeprefix("GRB")])
    return [{k: (None if pd.isna(v) else v) for k, v in row.items()} for row in df.to_dict("records")]


def build_latex_table(results):
    """Render the per-episode Limit-B Gamma_min table.

    Bursts without a redshift never yield a Gamma_min (z enters d_L in tau_hat), so
    they are dropped from the table entirely rather than shown as all-ellipsis rows
    -- the CSV keeps every row regardless, this is a table-only presentation choice.
    """
    results = [r for r in results if r["z"] is not None]
    # See generate_lorentz_table.py::build_latex_table()'s identical sort for why.
    results = sorted(results, key=lambda r: (r["GRB"], episode_order(r["episode"])))
    seed = int(results[0]["seed"])

    rows = ""
    current = None
    for r in results:
        if r["GRB"] != current:
            if current is not None:
                rows += "    \\midrule\n"
            rows += f"    \\multicolumn{{4}}{{l}}{{\\textbf{{{r['tex_name']}}}}} \\\\\n"
            current = r["GRB"]

        gamma = None if r["Gamma_min_B"] is None else round(r["Gamma_min_B"])
        if gamma is None:
            gamma_str = r"\ldots"
        else:
            gamma_str = f"${gamma}_{{-{r['Gamma_min_B_err_lower']:.0f}}}^{{+{r['Gamma_min_B_err_upper']:.0f}}}$"

        rows += (
            f"    {r['episode']} & "
            f"{fmt_t_v(r)} & {fmt(r['beta'], '.3f')} & {gamma_str} \\\\\n"
        )

    return (
        "% AUTO-GENERATED by codes-for-paper/lorentz_factor/generate_lorentz_table_limit_b.py\n"
        "% Do not edit by hand — regenerate from lorentz_results_limit_b.csv instead.\n"
        r"""\begin{table}[!ht]
\centering
\caption{
Minimum bulk Lorentz factor $\Gamma_{\min}$ from Compton scattering off pair-produced $e^{\pm}$ (Lithwick \& Sari 2001, Limit B), evaluated for every episode with \ac{LAT} coverage -- the same episode set as the Limit A table (\ref{tab:lorentz}).
Unlike Limit A, this bound does not depend on the LAT photon energy, so it applies equally to episodes whose highest-energy photon is a low-significance association.
$t_{\rm v}$ the variability timescale, $\beta$ the high-energy photon index of the episode's best-fit model, and $\Gamma_{\min}$ the derived lower limit~\citep{Lithwick2001}.
Errors are the statistical $1\sigma$ interval from $10^{4}$ Monte Carlo draws (seed __SEED__) of the spectral parameters (and, for a $\dagger$-free $t_{\rm v}$, of $t_{\rm v}$'s own measured uncertainty as well); as with Limit A they are far smaller than the systematic uncertainty from the analytic approximation adopted.
Only \grbzeroeightzeroninesixteenC\ has a confirmed spectroscopic redshift ($z = 4.35$); the other three bursts lack a measured redshift, so $\Gamma_{\min}$ is undetermined for them and they are omitted from this table.
}
\label{tab:lorentz_limit_b}
\begin{threeparttable}
\renewcommand{\arraystretch}{1.25}
\resizebox{\columnwidth}{!}{
\begin{tabular}{lccc}
\toprule
Episode & $t_{\rm v}$ [s] & $\beta$ & $\Gamma_{\min}$ \\
\midrule
"""
        + rows
        + r"""\bottomrule
\end{tabular}
}
\begin{tablenotes}
\footnotesize
\item[$\dagger$] Episode duration adopted as an upper bound on the variability timescale, giving a conservative $\Gamma_{\min}$.
\item[$\ast$] Measured variability timescale from a joint Norris-pulse fit to the light curve, given with its $1\sigma$ Monte Carlo uncertainty.
\end{tablenotes}
\end{threeparttable}
\end{table}
"""
    ).replace("__SEED__", str(seed))


def main():
    results = load_results()
    TABLE_TEX.write_text(build_latex_table(results))
    print(f"Saved: {TABLE_TEX}")


if __name__ == "__main__":
    main()
