"""
Combined Limit A + Limit B Gamma_min table
=====================================================
Join-only: reads ``lorentz_results.csv`` and ``lorentz_results_limit_b.csv`` on
``GRB``+``episode`` and renders ``lorentz_table_combined.tex``. Recomputes nothing and
touches neither limit's script or seed.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from generate_lorentz_table import TEX_NAMES, episode_order, fmt, fmt_t_v

HERE = Path(__file__).parent
TABLE_TEX = HERE / "lorentz_table_combined.tex"


def gamma_str(r, col):
    if r[col] is None:
        return r"\ldots"
    return f"${round(r[col])}_{{-{r[col + '_err_lower']:.0f}}}^{{+{r[col + '_err_upper']:.0f}}}$"


def load_joined():
    a = pd.read_csv(HERE / "lorentz_results.csv")
    b = pd.read_csv(HERE / "lorentz_results_limit_b.csv")
    b = b[["GRB", "episode", "Gamma_min_B", "Gamma_min_B_err_lower", "Gamma_min_B_err_upper", "seed"]]
    df = a.merge(b, on=["GRB", "episode"], how="inner", suffixes=("", "_B"))
    assert len(df) == len(a) == len(b), "Limit A / Limit B episode sets differ"
    df["tex_name"] = df["GRB"].map(lambda g: TEX_NAMES[g.removeprefix("GRB")])
    return [{k: (None if pd.isna(v) else v) for k, v in row.items()} for row in df.to_dict("records")]


def build_latex_table(results):
    results = [r for r in results if r["z"] is not None]
    results = sorted(results, key=lambda r: (r["GRB"], episode_order(r["episode"])))
    seed_a, seed_b = int(results[0]["seed"]), int(results[0]["seed_B"])

    rows, current = "", None
    for r in results:
        if r["GRB"] != current:
            if current is not None:
                rows += "    \\midrule\n"
            rows += f"    \\multicolumn{{7}}{{l}}{{\\textbf{{{r['tex_name']}}}}} \\\\\n"
            current = r["GRB"]
        rows += (
            f"    {r['episode']} & {fmt(r['E_max_MeV'] / 1e3, '.2f')} & "
            f"{fmt(r['t_arr_s'], '.2f')} & {fmt_t_v(r)} & {fmt(r['beta'], '.3f')} & "
            f"{gamma_str(r, 'Gamma_min')} & {gamma_str(r, 'Gamma_min_B')} \\\\\n"
        )

    return (
        "% PROTOTYPE -- generated by generate_lorentz_table_combined.py (join of the two CSVs); do not edit by hand\n"
        r"""\begin{table}[!ht]
\centering
\caption{Minimum bulk Lorentz factor $\Gamma_{\min}$ for every episode with \ac{LAT} coverage, from the two limits of \citet{Lithwick2001}.
$E_{\rm GeV}$ and $t_{\rm arr}$ are the energy and arrival time (relative to $T_0$) of the episode's highest-energy \ac{LAT} photon; $t_{\rm v}$ is the variability timescale and $\beta$ the high-energy photon index of the best-fit model.
Errors are the statistical $1\sigma$ interval from $10^{4}$ Monte Carlo draws (seeds __SEED_A__ for A, __SEED_B__ for B) of the spectral parameters. %; they are far smaller than the systematic uncertainty from the analytic approximation adopted.
% Only \grbzeroeightzeroninesixteenC\ has a confirmed spectroscopic redshift ($z = 4.35$); the other three bursts lack one and are omitted.
}
\label{tab:lorentz_combined}
\resizebox{\columnwidth}{!}{
\begin{threeparttable}
\renewcommand{\arraystretch}{1.25}
\begin{tabular}{lcccccc}
\toprule
Episode & $E_{\rm GeV}$ [GeV] & $t_{\rm arr}$ [s] &
    $t_{\rm v}$ [s] & $\beta$ & $\Gamma_{\min,A}$ & $\Gamma_{\min,B}$ \\
\midrule
"""
        + rows
        + r"""\bottomrule
\end{tabular}
\begin{tablenotes}
\footnotesize
\item[$\dagger$] Episode duration adopted as an upper bound on the variability timescale, giving a conservative $\Gamma_{\min}$.
\end{tablenotes}
\end{threeparttable}
}
\end{table}
"""
    ).replace("__SEED_A__", str(seed_a)).replace("__SEED_B__", str(seed_b))


def main():
    TABLE_TEX.write_text(build_latex_table(load_joined()))
    print(f"Saved: {TABLE_TEX}")


if __name__ == "__main__":
    main()
