dependencies:
    - conda-forge::numpy<2
    - conda-forge::pip
    -   pip:
            - matplotlib
            - uncertainties
            - pandas
            - seaborn
            - astropy
            - scipy
            - tqdm
            - showyourwork
            - pulp<2.8.0
