dependencies:
  - conda-forge::numpy<2
  - conda-forge::pip
  - conda-forge::python=3.11
  - pip:
      - matplotlib
      - uncertainties
      - pandas
      - seaborn
      - astropy
      - scipy
      - tqdm
      - pulp<2.8.0
