"""Generate the paper's canonical RNG-seed table.

This is a root-level script, not inside any topic folder.
The table it produces spans every topic folder's own script (`fluence`, `lorentz_factor`, `bb_fraction`, ...) rather
than belonging to one of them -- and it isn't part of the core `src/grb_research/` library either, since it's
paper-output plumbing, not analysis code.

Reference implementation for this convention: `codes-for-paper/amati_relationship/csv_to_latex.py`
(read the CSV, emit the paper's macros/table, never retype numbers into the `.tex`).

Source data lives in `seed_registry.yaml` (slug -> script, categorized active/unused/dormant -- see that file's header).
Only the script path is stored there; every seed is computed live via `seed_from_name`, never hardcoded, so this can
never drift from what each script actually uses.

Output goes to `seed_table.csv` and `seed_table.tex` here and is copied into `GRBResearchPaper/tex_files/generated/`;
the two repos are independent, so that copy is manual (the same as every other generated table -- BUGS.md BUG-10).
"""

from pathlib import Path

import pandas as pd
import yaml

from grb_research import MASTER_SEED, seed_from_name

ROOT = Path(__file__).parent
REGISTRY_PATH = ROOT / "seed_registry.yaml"
CSV_PATH = ROOT / "seed_table.csv"
TEX_PATH = ROOT / "seed_table.tex"

with open(REGISTRY_PATH) as f:
    registry = yaml.safe_load(f)

rows = []
for status in ("active", "unused", "dormant"):
    for slug, entry in registry.get(status, {}).items():
        rel_path = entry["script"]
        assert (ROOT / rel_path).is_file(), f"{status}/{slug}: script not found on disk: {rel_path}"
        rows.append(
            {
                "slug": slug,
                "status": status,
                "script": rel_path,
                "seed": seed_from_name(Path(rel_path).name),
                "item": entry.get("item", ""),
                "cref": entry.get("cref", ""),
                "note": entry.get("note", ""),
            }
        )

df = pd.DataFrame(rows)
df.to_csv(CSV_PATH, index=False)

active_rows = [r for r in rows if r["status"] == "active"]

CAPTION_SENTENCES = [
    r"Deterministic per-script Monte Carlo seed for every script in this project's analysis pipeline that performs "
    r"random sampling, each derived by hashing the script's file name together with a master seed of "
    + str(MASTER_SEED) + ".",
    r"The master seed itself was drawn from a cryptographic random-number generator prior to any analysis, so it is "
    r"auditable and was not chosen to influence any result.",
    r"Deriving each script's seed this way, rather than sharing one literal value, ensures independent analyses draw "
    r"from independent, uncorrelated random streams while remaining exactly reproducible from this table alone.",
]

lines = [
    "% AUTO-GENERATED by codes-for-paper/seed_table_to_latex.py from codes-for-paper/seed_registry.yaml",
    "% Do not hand-edit: regenerate that script and copy the result here.",
    r"\begin{table*}[!ht]",
    r"    \centering",
    r"    \caption{",
]
lines += [f"        {sentence}" for sentence in CAPTION_SENTENCES]
lines += [
    r"    }",
    r"    \label{tab:seed_table}",
    r"    \resizebox{\textwidth}{!}{",
    r"    \begin{tabular}{rll}",
    r"        \toprule",
    r"        Seed & Item & Fig./Table \\",
    r"        \midrule",
]
for row in active_rows:
    lines.append(f"        {row['seed']} & {row['item']} & {row['cref']} \\\\")
lines += [
    r"        \bottomrule",
    r"    \end{tabular}",
    r"    }",
    r"\end{table*}",
]

TEX_PATH.write_text("\n".join(lines) + "\n")
print(f"Saved: {CSV_PATH.name} ({len(rows)} rows: {len(active_rows)} active, "
      f"{sum(r['status'] == 'unused' for r in rows)} unused, {sum(r['status'] == 'dormant' for r in rows)} dormant)")
print(f"Saved: {TEX_PATH.name} ({len(active_rows)} rows)")
