"""Convert amati_relationship_unknown_z.csv to a LaTeX table for the three bursts with no
measured redshift (GRB131014A, GRB140206B, GRB231129C) -- a second table alongside tab:eiso
(GRB080916C only, csv_to_latex.py), not merged into it.

Design (2026-09-30 review of an earlier min-max-range draft):
  - E_i,peak is dropped. E_i,peak = (1+z) E_p,obs is an exact identity (the underlying spectral
    fit sample is drawn once and merely rescaled by (1+z) for each z, never refit), so showing
    it swept over z carries zero information beyond E_p,obs itself -- confirmed empirically too:
    every row's z=1-vs-z=7-implied E_p,obs agrees to <0.3% (pure MC noise; see amati_relationship.py's
    console output). One E_p,obs column, point + error, plus this caption sentence, says the same
    thing as a 4-column E_i,peak sweep in a quarter of the space.
  - E_iso does NOT reduce to a fixed multiple of E_p,obs -- it runs through d_L(z)^2 and a
    per-episode K-correction, so it gets one column per swept z (1, 3, 5, 7), not a min-max range
    that would hide the (non-uniform, burst-dependent) shape of that growth.

2026-09-30, later same day: this version shows each Eiso cell as value +- MC error rather than a
bare median. An earlier draft omitted the error (checked, not assumed, to be negligible -- 0.4-3.6%
of the value at every z, against a 37-650% change between adjacent z columns -- and said so in the
caption instead of showing it per cell); that draft is kept for comparison in
_backup_2026-09-30_bare_eiso/. The negligibility finding itself still holds -- this is a
presentation choice (bare medians read as sparse/incomplete against the rest of this paper's
tables, all of which are point+error), not a retraction of that finding.
"""

import numpy as np
import pandas as pd

from csv_to_latex import decimals_for, format_grb_name, format_model_name, format_value_with_errors

Z_VALUES = (1, 3, 5, 7)


def csv_to_latex_table(csv_path="amati_relationship_unknown_z.csv",
                       output_path="amati_relationship_unknown_z_table.tex"):
    df = pd.read_csv(csv_path)
    seed = int(df["seed"].iloc[0])

    ep_decimals = decimals_for(np.r_[df["E_p_obs_err_lower__1e+03_keV"], df["E_p_obs_err_upper__1e+03_keV"]])
    # One shared decimal count across all four z columns, derived from every z's own error rather
    # than each z picking its own precision -- keeps the four Eiso columns visually aligned.
    ei_err_cols = np.r_[[df[f"E_0_iso_z{z}_err_lower__1e+52_erg"] for z in Z_VALUES]].ravel()
    ei_err_cols = np.r_[ei_err_cols, np.r_[[df[f"E_0_iso_z{z}_err_upper__1e+52_erg"] for z in Z_VALUES]].ravel()]
    ei_decimals = decimals_for(ei_err_cols)

    latex_lines = []
    latex_lines.append("% AUTO-GENERATED by codes-for-paper/amati_relationship/csv_to_latex_unknown_z.py")
    latex_lines.append("% Do not edit by hand — regenerate from amati_relationship_unknown_z.csv instead.")
    latex_lines.append("\\begin{table}[!ht]")
    latex_lines.append("    \\centering")
    # Kept short deliberately -- the (1+z) identity and the MC-vs-z-spread justification for the
    # design (why E_i,peak isn't a column, why Eiso has no per-cell error) live in the prose of
    # section-5-data-analysis.tex right before \input{tex_files/generated/amati_relationship_unknown_z_table},
    # not duplicated here; captions in this paper are kept to what the table itself shows.
    latex_lines.append(
        "    \\caption{Observed peak energy $E_\\text{p}$ and isotropic equivalent energy \\eiso\\ "
        "for the three bursts without a measured redshift, at four assumed redshifts $z=1, 3, 5, 7$.\n"
        f"        Values are the median and asymmetric $1\\sigma$ error from $10^4$ Monte Carlo "
        f"samples (seed ${seed}$).}}"
    )
    latex_lines.append("    \\label{tab:eiso-unknown-z}")
    latex_lines.append("    \\renewcommand{\\arraystretch}{1.25}")
    latex_lines.append("    \\resizebox{\\columnwidth}{!}{")
    latex_lines.append("    \\begin{tabular}{lccccccc}")
    latex_lines.append("        \\toprule")
    latex_lines.append(
        "        Model & Episode & $E_{\\mathrm{p}}$ [MeV] & "
        "\\multicolumn{4}{c}{$E^{52}_{\\mathrm{iso}}$ [erg]} \\\\"
    )
    latex_lines.append(
        "         & & & $z=1$ & $z=3$ & $z=5$ & $z=7$ \\\\"
    )
    latex_lines.append("        \\midrule")

    # GRB names as their own \multicolumn header row per group, not a repeated/blank leading
    # column -- same convention as csv_to_latex.py's known-redshift table and both Lorentz
    # tables, and one fewer column here where the table was already dense (8 columns -> 7).
    current_grb = None
    for idx, row in df.iterrows():
        grb_name = row["GRBName"]
        if grb_name != current_grb:
            if idx != 0:
                latex_lines.append("        \\midrule")
            grb_display = format_grb_name(grb_name)
            latex_lines.append(f"        \\multicolumn{{7}}{{l}}{{\\textbf{{{grb_display}}}}} \\\\")
            current_grb = grb_name

        model_name = format_model_name(row["Model"])
        ep_str = format_value_with_errors(
            row["E_p_obs__1e+03_keV"],
            row["E_p_obs_err_lower__1e+03_keV"],
            row["E_p_obs_err_upper__1e+03_keV"],
            decimals=ep_decimals,
        )
        ei_strs = " & ".join(
            format_value_with_errors(
                row[f"E_0_iso_z{z}__1e+52_erg"],
                row[f"E_0_iso_z{z}_err_lower__1e+52_erg"],
                row[f"E_0_iso_z{z}_err_upper__1e+52_erg"],
                decimals=ei_decimals,
            )
            for z in Z_VALUES
        )

        latex_lines.append(f"        {model_name} & {row['EpisodeName']} & {ep_str} & {ei_strs} \\\\")

    latex_lines.append("        \\bottomrule")
    latex_lines.append("    \\end{tabular}")
    latex_lines.append("    }")
    latex_lines.append("\\end{table}")

    with open(output_path, "w") as f:
        f.write("\n".join(latex_lines))

    print(f"LaTeX table written to {output_path}")
    print(f"Total rows: {len(df)}")
    print("\n" + "=" * 80)
    for line in latex_lines:
        print(line)


if __name__ == "__main__":
    csv_to_latex_table()
