"""Convert amati_relationship.csv to LaTeX table format."""

import numpy as np
import pandas as pd


# Significant figures to preserve on the smallest error in a column.
ERROR_SIG_FIGS = 2


def decimals_for(errors, norm=1.0, sig=ERROR_SIG_FIGS, cap=6):
    """Decimal places such that the smallest error in a column keeps `sig` digits.

    Derived from the data rather than hardcoded, so the table cannot silently
    lose precision -- or print spurious precision -- if the inputs change.
    """
    values = np.asarray(errors, dtype=float) / norm
    values = values[np.isfinite(values) & (values > 0)]
    if values.size == 0:
        return 2
    return max(0, min(int(sig - 1 - np.floor(np.log10(values.min()))), cap))


def format_value_with_errors(value, err_lower, err_upper, scientific=False, decimals=3):
    """
    Format a value with asymmetric errors for LaTeX.

    Parameters
    ----------
    value :
        Central value
    err_lower :
        Lower error (positive value)
    err_upper :
        Upper error (positive value)
    scientific :
        Use scientific notation
    decimals :
        Number of decimal places

    Returns
    -------
    str
        LaTeX formatted string like $value_{-lower}^{+upper}$
    """
    if scientific:
        # Format in scientific notation
        exp = int(np.floor(np.log10(abs(value))))
        val_mantissa = value / (10**exp)
        err_l_mantissa = err_lower / (10**exp)
        err_u_mantissa = err_upper / (10**exp)

        return f"${val_mantissa:.{decimals}f}_{{-{err_l_mantissa:.{decimals}f}}}^{{+{err_u_mantissa:.{decimals}f}}} \\times 10^{{{exp}}}$"
    else:
        return f"${value:.{decimals}f}_{{-{err_lower:.{decimals}f}}}^{{+{err_upper:.{decimals}f}}}$"


# The paper defines a macro per burst (preamble.tex) so names stay consistent
# everywhere; emit those rather than literal text.
GRB_TEX_MACROS = {
    "GRB080916C": r"\grbzeroeightzeroninesixteenC",
    "GRB131014A": r"\grbthirteentenfourteenA",
    "GRB140206B": r"\grbfourteenzerotwozerosixB",
    "GRB231129C": r"\grbtwentythreeeleventwentynineC",
}


def format_grb_name(grb_name):
    """Format GRB name for LaTeX, using the paper's per-burst macro."""
    return GRB_TEX_MACROS.get(grb_name, grb_name)


def format_model_name(model_name):
    """Format model name for LaTeX, using the paper's per-model macro.

    The preamble defines one macro per model combination, named as the
    lower-cased model with separators removed: ``SBPL_BB`` -> ``\\sbplbb``.
    """
    return "\\" + model_name.lower().replace("_", "")


def csv_to_latex_table(csv_path="amati_relationship.csv", output_path="amati_relationship_table.tex"):
    """
    Convert the Amati relationship CSV to a LaTeX table.

    Parameters
    ----------
    csv_path :
        Path to input CSV file
    output_path :
        Path to output LaTeX file
    """
    # Read CSV
    df = pd.read_csv(csv_path)

    ep_decimals = decimals_for(
        np.r_[df["E_i_peak_err_lower__1e+03_keV"], df["E_i_peak_err_upper__1e+03_keV"]]
    )
    ei_decimals = decimals_for(
        np.r_[df["E_0_iso_err_lower__1e+52_erg"], df["E_0_iso_err_upper__1e+52_erg"]]
    )

    # Start building LaTeX table
    latex_lines = []
    latex_lines.append("% AUTO-GENERATED by codes-for-paper/amati_relationship/csv_to_latex.py")
    latex_lines.append("% Do not edit by hand — regenerate from amati_relationship.csv instead.")
    latex_lines.append("\\begin{table}[!ht]")
    latex_lines.append("    \\centering")
    latex_lines.append(
        "    \\caption{Intrinsic peak energy $E_\\text{i,p}$ and isotropic equivalent energy \\eiso "
        "for the time-integrated and time-resolved episodes of GRBs with known redshifts.\n"
        "        Values are the median and the asymmetric errors on the posterior distribution "
        "derived from $10^4$ MCMC samples.}"
    )
    latex_lines.append("    \\label{tab:eiso}")
    latex_lines.append("    \\renewcommand{\\arraystretch}{1.25}")
    latex_lines.append("    \\resizebox{\\columnwidth}{!}{")
    latex_lines.append("    \\begin{tabular}{lccc}")
    latex_lines.append("        \\toprule")
    latex_lines.append(
        "        Model & Episode & " "$E_{i,\\mathrm{peak}}$ [MeV] & $E^{52}_{\\mathrm{iso}}$ [erg] \\\\"
    )
    latex_lines.append("        \\midrule")

    current_grb = None

    for idx, row in df.iterrows():
        grb_name = row["GRBName"]
        model_name = format_model_name(row["Model"])
        episode_name = row["EpisodeName"]

        # Add GRB header when we encounter a new GRB
        if grb_name != current_grb:
            # Add multicolumn row for GRB name
            grb_display = format_grb_name(grb_name)
            if idx != 0:
                latex_lines.append("        \\midrule")
            latex_lines.append(f"        \\multicolumn{{4}}{{l}}{{\\textbf{{{grb_display}}}}} \\\\")
            current_grb = grb_name

        # Format E_peak with errors
        ep_val = row["E_i_peak__1e+03_keV"]
        ep_err_l = row["E_i_peak_err_lower__1e+03_keV"]
        ep_err_u = row["E_i_peak_err_upper__1e+03_keV"]

        # Determine if we should use scientific notation for E_peak
        if ep_val >= 10000:
            ep_str = format_value_with_errors(ep_val, ep_err_l, ep_err_u, scientific=True, decimals=ep_decimals)
        else:
            ep_str = format_value_with_errors(ep_val, ep_err_l, ep_err_u, scientific=False, decimals=ep_decimals)

        # Format E_iso with errors
        ei_val = row["E_0_iso__1e+52_erg"]
        ei_err_l = row["E_0_iso_err_lower__1e+52_erg"]
        ei_err_u = row["E_0_iso_err_upper__1e+52_erg"]
        ei_str = format_value_with_errors(ei_val, ei_err_l, ei_err_u, scientific=False, decimals=ei_decimals)

        # Build table row
        latex_lines.append(f"        {model_name} & {episode_name} & " f"{ep_str} & {ei_str} \\\\")

    latex_lines.append("        \\bottomrule")
    latex_lines.append("    \\end{tabular}")
    latex_lines.append("    }")
    latex_lines.append("\\end{table}")

    # Write to file
    with open(output_path, "w") as f:
        f.write("\n".join(latex_lines))

    print(f"LaTeX table written to {output_path}")
    print(f"Total rows: {len(df)}")

    # Also print to console
    print("\n" + "=" * 80)
    print("LaTeX Table Preview:")
    print("=" * 80)
    for line in latex_lines:
        print(line)


if __name__ == "__main__":
    csv_to_latex_table()
