"""Convert amati_relationship_unknown_z.csv to a LaTeX table for the three bursts with no
measured redshift (GRB131014A, GRB140206B, GRB231129C) -- a second table alongside tab:eiso
(GRB080916C only, csv_to_latex.py), not merged into it.

Design (2026-09-30 review of an earlier min-max-range draft):
  - E_i,peak is dropped. E_i,peak = (1+z) E_p,obs is an exact identity (the underlying spectral
    fit sample is drawn once and merely rescaled by (1+z) for each z, never refit), so showing
    it swept over z carries zero information beyond E_p,obs itself -- confirmed empirically too:
    every row's z=1-vs-z=7-implied E_p,obs agrees to <0.3% (pure MC noise; see amati_relationship.py's
    console output). One E_p,obs column, point + error, plus this caption sentence, says the same
    thing as a 4-column E_i,peak sweep in a quarter of the space.
  - E_iso does NOT reduce to a fixed multiple of E_p,obs -- it runs through d_L(z)^2 and a
    per-episode K-correction, so it gets one column per swept z (1, 3, 5, 7), not a min-max range
    that would hide the (non-uniform, burst-dependent) shape of that growth.
  - E_iso's own MC statistical error is not shown per cell: checked, not assumed -- it is 0.4-3.6%
    of the value at every z, while the value itself changes 37-650% between adjacent z columns,
    stated in the caption instead of cluttering every cell with a negligible error bar.
"""

import numpy as np
import pandas as pd

from csv_to_latex import decimals_for, format_grb_name, format_model_name, format_value_with_errors

Z_VALUES = (1, 3, 5, 7)


def csv_to_latex_table(csv_path="amati_relationship_unknown_z.csv",
                       output_path="amati_relationship_unknown_z_table.tex"):
    df = pd.read_csv(csv_path)
    seed = int(df["seed"].iloc[0])

    ep_decimals = decimals_for(np.r_[df["E_p_obs_err_lower__1e+03_keV"], df["E_p_obs_err_upper__1e+03_keV"]])
    # One shared decimal count across all four z columns, from the smallest z=7 value (the
    # largest-magnitude column, since Eiso grows with z) down to z=1's smallest -- keeps every
    # column visually aligned rather than each z picking its own precision.
    ei_decimals = decimals_for(df["E_0_iso_z1__1e+52_erg"])

    latex_lines = []
    latex_lines.append("% AUTO-GENERATED by codes-for-paper/amati_relationship/csv_to_latex_unknown_z.py")
    latex_lines.append("% Do not edit by hand — regenerate from amati_relationship_unknown_z.csv instead.")
    latex_lines.append("\\begin{table}[!ht]")
    latex_lines.append("    \\centering")
    # Kept short deliberately -- the (1+z) identity and the MC-vs-z-spread justification for the
    # design (why E_i,peak isn't a column, why Eiso has no per-cell error) live in the prose of
    # section-5-data-analysis.tex right before \input{tex_files/generated/amati_relationship_unknown_z_table},
    # not duplicated here; captions in this paper are kept to what the table itself shows.
    latex_lines.append(
        "    \\caption{Observed peak energy $E_\\text{p}$ and isotropic equivalent energy \\eiso\\ "
        "for the three bursts without a measured redshift, at four assumed redshifts $z=1,3,5,7$.\n"
        f"        $E_\\text{{p}}$ is the median and asymmetric $1\\sigma$ error from $10^4$ Monte Carlo "
        f"samples (seed ${seed}$).}}"
    )
    latex_lines.append("    \\label{tab:eiso-unknown-z}")
    latex_lines.append("    \\renewcommand{\\arraystretch}{1.25}")
    latex_lines.append("    \\resizebox{\\columnwidth}{!}{")
    latex_lines.append("    \\begin{tabular}{llcccccc}")
    latex_lines.append("        \\toprule")
    latex_lines.append(
        "        GRB & Model & Episode & $E_{\\mathrm{p}}$ [MeV] & "
        "\\multicolumn{4}{c}{$E^{52}_{\\mathrm{iso}}$ [erg]} \\\\"
    )
    latex_lines.append(
        "         & & & & $z=1$ & $z=3$ & $z=5$ & $z=7$ \\\\"
    )
    latex_lines.append("        \\midrule")

    current_grb = None
    for idx, row in df.iterrows():
        grb_name = row["GRBName"]
        if grb_name != current_grb:
            if idx != 0:
                latex_lines.append("        \\midrule")
            current_grb = grb_name
        grb_display = format_grb_name(grb_name) if row.name == df[df["GRBName"] == grb_name].index[0] else ""

        model_name = format_model_name(row["Model"])
        ep_str = format_value_with_errors(
            row["E_p_obs__1e+03_keV"],
            row["E_p_obs_err_lower__1e+03_keV"],
            row["E_p_obs_err_upper__1e+03_keV"],
            decimals=ep_decimals,
        )
        ei_strs = " & ".join(f"${row[f'E_0_iso_z{z}__1e+52_erg']:.{ei_decimals}f}$" for z in Z_VALUES)

        latex_lines.append(
            f"        {grb_display} & {model_name} & {row['EpisodeName']} & {ep_str} & {ei_strs} \\\\"
        )

    latex_lines.append("        \\bottomrule")
    latex_lines.append("    \\end{tabular}")
    latex_lines.append("    }")
    latex_lines.append("\\end{table}")

    with open(output_path, "w") as f:
        f.write("\n".join(latex_lines))

    print(f"LaTeX table written to {output_path}")
    print(f"Total rows: {len(df)}")
    print("\n" + "=" * 80)
    for line in latex_lines:
        print(line)


if __name__ == "__main__":
    csv_to_latex_table()
