"""Generate the paper's time-integrated / time-resolved duration table.

This reproduces the table `\\input` by ``tex_files/section-3-data-preparation-and-analysis.tex`` in
``GRBResearchPaper``: for each of the four sample GRBs, the T90 window and every TR/EX episode's
time interval relative to trigger. Every number here is a raw interval boundary straight out of
``results.json`` -- no fit, no MC, no derived physics -- so unlike the other ``csv_to_latex.py``
scripts in this project there is no intermediate CSV: this script reads ``results.json`` directly
via ``TimeInterval.from_string`` (``src/grb_research/grb_time.py``), exactly as documented under
"Episode naming" in CLAUDE.md.

This table used to be hand-typed directly into an appendix file, with no generator anywhere in
this repo (table_registry.yaml's `no_known_source` section, until this script was added) -- the
live risk CLAUDE.md's "Generated LaTeX tables" section warns about (E_iso table drift, BUG-10).

Output goes to time_integrated_table.tex here and is copied into
GRBResearchPaper/tex_files/generated/ by codes-for-paper/sync_paper_assets.py (table_registry.yaml);
the section file `\\input`s that path directly (as of 2026-09-06, no intermediate wrapper file --
see table_registry.yaml's header comment for why the earlier per-table wrapper was dropped).
"""

from __future__ import annotations

import json
from pathlib import Path

from grb_research import find_project_root
from grb_research.grb_constants import short_to_long
from grb_research.grb_time import EpisodeTypes, TimeInterval

OUT_PATH = Path(__file__).parent / "time_integrated_table.tex"

# The paper's sample, in the order the table displays them -- not alphabetical. Per CLAUDE.md's
# "Research scope", these four (not the other four raw-interval directories in this repo).
GRB_ORDER = ["080916C", "131014A", "140206B", "231129C"]

TEX_NAMES = {
    "080916C": r"\grbzeroeightzeroninesixteenC",
    "131014A": r"\grbthirteentenfourteenA",
    "140206B": r"\grbfourteenzerotwozerosixB",
    "231129C": r"\grbtwentythreeeleventwentynineC",
}


def episode_label(interval: TimeInterval) -> str:
    """Short episode label, e.g. T90, EX0, TR1."""
    if interval.kind is EpisodeTypes.TR:
        return f"TR{interval.index}"
    return interval.kind.value


def load_intervals(results_path: Path) -> dict[str, dict[str, TimeInterval]]:
    """Every episode's TimeInterval for each sample GRB, keyed by episode label.

    Raises if a results.json key fails to parse (EpisodeTypes.UNKNOWN) -- a silent skip here would
    quietly drop a row from the paper's table instead of failing loudly (CLAUDE.md: "An input that
    genuinely cannot be derived must fail loudly").
    """
    data = json.loads(results_path.read_text())

    per_grb: dict[str, dict[str, TimeInterval]] = {}
    for short_name in GRB_ORDER:
        long_key = short_to_long[short_name]
        intervals: dict[str, TimeInterval] = {}
        for raw_key in data[long_key]:
            interval = TimeInterval.from_string(raw_key)
            if interval.kind is EpisodeTypes.UNKNOWN:
                raise ValueError(f"Unparsed results.json interval for GRB{short_name}: {raw_key!r}")
            intervals[episode_label(interval)] = interval
        per_grb[short_name] = intervals

    return per_grb


def cell(intervals: dict[str, TimeInterval], label: str) -> str:
    """One table cell: the interval's duration macro, or a dash if this GRB has no such episode."""
    interval = intervals.get(label)
    if interval is None:
        return r"\tabledash"
    return rf"\sirangeDuration{{{interval.start:.3f}}}{{{interval.end:.3f}}}"


def build_table(per_grb: dict[str, dict[str, TimeInterval]]) -> str:
    """Render the whole appendix table."""
    max_tr = max(
        interval.index
        for intervals in per_grb.values()
        for interval in intervals.values()
        if interval.kind is EpisodeTypes.TR
    )
    # (display label, lookup key) -- TR rows show the bare index but look up "TR<n>" in the
    # per-GRB interval dict, matching this table's existing (pre-automation) row labeling.
    resolved_rows = [("EX0", "EX0")] + [(str(n), f"TR{n}") for n in range(1, max_tr + 1)] + [("EX1", "EX1")]

    header_cells = " &\n        ".join(TEX_NAMES[short] for short in GRB_ORDER)

    integrated_cells = " &\n        ".join(cell(per_grb[short], "T90") for short in GRB_ORDER)

    resolved_lines = []
    for display_label, lookup_key in resolved_rows:
        row_cells = " &\n        ".join(cell(per_grb[short], lookup_key) for short in GRB_ORDER)
        resolved_lines.append(f"        {display_label} &\n        {row_cells} \\\\")
    resolved_body = "\n".join(resolved_lines)

    return (
        "% AUTO-GENERATED by codes-for-paper/time_integrated_table/time_integrated_table.py\n"
        "% Do not edit by hand -- regenerate from results.json instead.\n"
        r"""\begin{table*}[!ht]
    \caption{
        Time-integrated and time-resolved duration for the selected GRBs.
        The EX episodes are outside the standard \tnty~duration, taken to accommodate excess onset or fading tail release of GRBs.
    }
    \label{table:time-integrated-duration}
    \centering
    \resizebox{\textwidth}{!}{
    \begin{tabular}{ccccc}
        \toprule
        Episode &
        """
        + header_cells
        + r""" \\ \midrule
        \multicolumn{5}{l}{\textbf{Time-integrated}}\\
        \tnty &
        """
        + integrated_cells
        + r""" \\ \midrule
        \multicolumn{5}{l}{\textbf{Time-resolved}}\\
"""
        + resolved_body
        + r"""
        \bottomrule
    \end{tabular}
    }
\end{table*}
"""
    )


def main():
    """Read results.json and write the appendix table."""
    root = find_project_root()
    per_grb = load_intervals(root / "results.json")
    OUT_PATH.write_text(build_table(per_grb))
    n_episodes = sum(len(intervals) for intervals in per_grb.values())
    print(f"Saved: {OUT_PATH}  ({len(per_grb)} GRBs, {n_episodes} episodes)")


if __name__ == "__main__":
    main()
