"""Convert pe_er_photosphere.csv to the paper's LaTeX table.

Follows codes-for-paper/amati_relationship/csv_to_latex.py: read the CSV, emit
the paper's \\grb... and model macros, write a self-labelled table that
section-5 \\input's. Never hand-edit the generated .tex.

Only one redshift per interval is tabulated -- the spectroscopic value where one
exists, otherwise the fiducial sweep value. The full z dependence is the
figure's job, not the table's.
"""

import numpy as np
import pandas as pd

GRB_TEX_MACROS = {
    "GRB080916C": r"\grbzeroeightzeroninesixteenC",
    "GRB131014A": r"\grbthirteentenfourteenA",
    "GRB140206B": r"\grbfourteenzerotwozerosixB",
    "GRB231129C": r"\grbtwentythreeeleventwentynineC",
}

Z_FIDUCIAL = 2.0


def format_grb_name(grb_name):
    """Format a GRB name using the paper's per-burst macro."""
    return GRB_TEX_MACROS.get(grb_name, grb_name)


def format_model_name(model_name):
    """Format a model name using the paper's per-model macro (SBPL_BB -> \\sbplbb)."""
    return "\\" + model_name.lower().replace("_", "")


# Column normalisations: each column is divided by a common power of ten carried
# in the header, so the exponent is stated once instead of on every row.
F_BB_NORM = 1e-3
R0_NORM = 1e7
R_PH_NORM = 1e11

# Significant figures to preserve on the smallest error in a column.
ERROR_SIG_FIGS = 2


def decimals_for(errors, norm, sig=ERROR_SIG_FIGS, cap=6):
    """Decimal places such that the smallest error in a column keeps `sig` digits.

    Derived from the data rather than hardcoded, so the table cannot silently
    lose precision if the inputs change.
    """
    values = np.asarray(errors, dtype=float) / norm
    values = values[np.isfinite(values) & (values > 0)]
    if values.size == 0:
        return 2
    return max(0, min(int(sig - 1 - np.floor(np.log10(values.min()))), cap))


def exponent_label(norm):
    """LaTeX for the power of ten a column is normalised by, e.g. 10^{11}."""
    return f"10^{{{int(np.log10(norm))}}}"


def format_normalised(value, err_lower, err_upper, norm, decimals):
    """Render value/norm with asymmetric errors, the exponent living in the header."""
    return (
        f"${value / norm:.{decimals}f}_{{-{err_lower / norm:.{decimals}f}}}" f"^{{+{err_upper / norm:.{decimals}f}}}$"
    )


def format_plain(value, err_lower, err_upper, decimals=0):
    """Render a value with asymmetric errors, no exponent."""
    return f"${value:.{decimals}f}_{{-{err_lower:.{decimals}f}}}^{{+{err_upper:.{decimals}f}}}$"


def select_rows(df):
    """One row per interval: the measured z, or the row nearest the fiducial z."""
    keep = []
    for (_, _), group in df.groupby(["grb_name", "episode"], sort=False):
        if (group["z_source"] == "spectroscopic").any():
            keep.append(group[group["z_source"] == "spectroscopic"].iloc[0])
        else:
            keep.append(group.iloc[(group["z"] - Z_FIDUCIAL).abs().argmin()])
    return pd.DataFrame(keep)


def csv_to_latex_table(csv_path="pe_er_photosphere.csv", output_path="photospheric_table.tex"):
    """Render the Pe'er+2007 fireball parameters as a LaTeX table."""
    df = select_rows(pd.read_csv(csv_path))
    f_bb_decimals = decimals_for(np.r_[df["f_bb_err_lower"], df["f_bb_err_upper"]], F_BB_NORM)
    r0_decimals = decimals_for(np.r_[df["r0_err_lower_cm"], df["r0_err_upper_cm"]], R0_NORM)
    r_ph_decimals = decimals_for(np.r_[df["r_ph_err_lower_cm"], df["r_ph_err_upper_cm"]], R_PH_NORM)

    n_samples = int(df["n_samples"].iloc[0])
    seed = int(df["seed"].iloc[0])

    lines = [
        "% AUTO-GENERATED by codes-for-paper/photospheric_radius/csv_to_latex.py",
        "% Do not edit by hand — regenerate from pe_er_photosphere.csv instead.",
        "\\begin{table*}[!ht]",
        "    \\centering",
        (
            "    \\caption{Fireball parameters derived from the thermal component following the method of "
            "\\citet{Peer2007}: the size at the base of the flow $r_0$, the bulk Lorentz factor $\\Gamma$, "
            "and the photospheric radius $r_\\mathrm{ph}$.\n"
            "        $\\mathcal{R} = (F_\\mathrm{BB}/\\sigma T_\\mathrm{ob}^4)^{1/2}$ and $f_\\mathrm{BB}$ are "
            "the observables entering their equations~(1), (4) and~(5).\n"
            "        Only \\grbzeroeightzeroninesixteenC\\ has a spectroscopic redshift; for the remaining "
            f"bursts values are quoted at a fiducial $z = {Z_FIDUCIAL:g}$ and the full redshift dependence is "
            "shown in \\cref{fig:photospheric}.\n"
            "        All values assume $Y = 1$, where $Y \\geq 1$ is the ratio of total fireball energy to "
            "the energy radiated in $\\gamma$-rays; the scalings are "
            "$\\Gamma \\propto Y^{1/4}$, $r_0 \\propto Y^{-3/2}$ and $r_\\mathrm{ph} \\propto Y^{1/4}$.\n"
            f"        All quantities carry asymmetric $1\\sigma$ intervals from ${n_samples}$ Monte Carlo samples "
            f"(seed ${seed}$), including $kT$, whose median here is the Monte Carlo-sampled statistic of the "
            "same fit reported directly (fit value and native error) in \\cref{tab:bbfraction}; the two are "
            "expected to agree only within the stated uncertainties, not exactly, since they summarize the "
            "same underlying distribution differently.}"
        ),
        "    \\label{tab:photospheric}",
        "    \\renewcommand{\\arraystretch}{1.25}",
        "    \\resizebox{\\textwidth}{!}{",
        "    \\begin{tabular}{lccccccc}",
        "        \\toprule",
        (
            "        Model & Episode & $z$ & $kT$ [keV] & "
            f"$f_\\mathrm{{BB}}$ [${exponent_label(F_BB_NORM)}$] & "
            f"$r_0$ [${exponent_label(R0_NORM)}$ cm] & $\\Gamma$ & "
            f"$r_\\mathrm{{ph}}$ [${exponent_label(R_PH_NORM)}$ cm] \\\\"
        ),
        "        \\midrule",
    ]

    current_grb = None
    for idx, (_, row) in enumerate(df.iterrows()):
        if row["grb_name"] != current_grb:
            if idx != 0:
                lines.append("        \\midrule")
            lines.append(f"        \\multicolumn{{8}}{{l}}{{\\textbf{{{format_grb_name(row['grb_name'])}}}}} \\\\")
            current_grb = row["grb_name"]

        z_cell = f"${row['z']:.2f}$" if row["z_source"] == "spectroscopic" else f"${row['z']:.2f}^{{\\dagger}}$"
        f_bb_cell = format_normalised(
            row["f_bb"], row["f_bb_err_lower"], row["f_bb_err_upper"], F_BB_NORM, f_bb_decimals
        )
        r0_cell = format_normalised(row["r0_cm"], row["r0_err_lower_cm"], row["r0_err_upper_cm"], R0_NORM, r0_decimals)
        r_ph_cell = format_normalised(
            row["r_ph_cm"], row["r_ph_err_lower_cm"], row["r_ph_err_upper_cm"], R_PH_NORM, r_ph_decimals
        )
        lines.append(
            f"        {format_model_name(row['model_name'])} & {row['episode']} & {z_cell} & "
            f"{format_plain(row['kt_bb_keV'], row['kt_bb_err_lower_keV'], row['kt_bb_err_upper_keV'], 2)} & "
            f"{f_bb_cell} & {r0_cell} & "
            f"{format_plain(row['Gamma'], row['Gamma_err_lower'], row['Gamma_err_upper'])} & "
            f"{r_ph_cell} \\\\"
        )

    lines += [
        "        \\midrule",
        "        \\multicolumn{8}{l}{\\footnotesize $^{\\dagger}$ Assumed fiducial redshift; "
        "no spectroscopic measurement exists for this burst.} \\\\",
        "        \\bottomrule",
        "    \\end{tabular}",
        "    }",
        "\\end{table*}",
    ]

    with open(output_path, "w") as handle:
        handle.write("\n".join(lines))

    print(f"LaTeX table written to {output_path}")
    print(f"Total rows: {len(df)}")


if __name__ == "__main__":
    csv_to_latex_table()
