"""Convert bb_flux_fraction.csv to the paper's LaTeX table.

Follows the same pattern as codes-for-paper/amati_relationship/csv_to_latex.py:
read the CSV, emit the paper's \\grb... and model macros, write a self-labelled
table that section-5 \\input's. Never hand-edit the generated .tex.

Only one redshift per interval is tabulated -- the spectroscopic value where
one exists, otherwise the fiducial sweep value -- mirroring
photospheric_radius/csv_to_latex.py exactly, since bb_flux_fraction.csv now
carries the same one-row-per-interval-per-redshift shape for the same reason.
The full z dependence of f_BB(rest) is the bb_flux_fraction_rest_vs_z figure's
job, not the table's.
"""

import numpy as np
import pandas as pd

# The paper defines a macro per burst (preamble.tex) so names stay consistent.
GRB_TEX_MACROS = {
    "GRB080916C": r"\grbzeroeightzeroninesixteenC",
    "GRB131014A": r"\grbthirteentenfourteenA",
    "GRB140206B": r"\grbfourteenzerotwozerosixB",
    "GRB231129C": r"\grbtwentythreeeleventwentynineC",
}

Z_FIDUCIAL = 2.0


def format_grb_name(grb_name):
    """Format a GRB name using the paper's per-burst macro."""
    return GRB_TEX_MACROS.get(grb_name, grb_name)


def format_model_name(model_name):
    """Format a model name using the paper's per-model macro (SBPL_BB -> \\sbplbb)."""
    return "\\" + model_name.lower().replace("_", "")


# Column normalisations: each column is divided by a common power of ten carried
# in the header, so the exponent is stated once instead of on every row.
FLUX_BB_NORM = 1e-6
FLUX_TOTAL_NORM = 1e-6
F_BB_NORM = 1e-3

# Significant figures to preserve on the smallest error in a column.
ERROR_SIG_FIGS = 2


def decimals_for(errors, norm, sig=ERROR_SIG_FIGS, cap=6):
    """Decimal places such that the smallest error in a column keeps `sig` digits.

    Derived from the data rather than hardcoded, so the table cannot silently
    lose precision if the inputs change. Example: a smallest normalised error of
    0.021 needs 3 decimals to show "0.021"; one of 4.6 needs 1 to show "4.6".
    """
    values = np.asarray(errors, dtype=float) / norm
    values = values[np.isfinite(values) & (values > 0)]
    if values.size == 0:
        return 2
    return max(0, min(int(sig - 1 - np.floor(np.log10(values.min()))), cap))


def format_normalised(value, err_lower, err_upper, norm, decimals):
    """Render value/norm with asymmetric errors, the exponent living in the header."""
    return (
        f"${value / norm:.{decimals}f}_{{-{err_lower / norm:.{decimals}f}}}"
        f"^{{+{err_upper / norm:.{decimals}f}}}$"
    )


def exponent_label(norm):
    """LaTeX for the power of ten a column is normalised by, e.g. 10^{-6}."""
    return f"10^{{{int(np.log10(norm))}}}"


def select_rows(df):
    """One row per interval: the measured z, or the row nearest the fiducial z.

    Mirrors photospheric_radius/csv_to_latex.py's select_rows exactly.
    """
    keep = []
    for (_, _), group in df.groupby(["grb_name", "episode"], sort=False):
        if (group["z_source"] == "spectroscopic").any():
            keep.append(group[group["z_source"] == "spectroscopic"].iloc[0])
        else:
            keep.append(group.iloc[(group["z"] - Z_FIDUCIAL).abs().argmin()])
    return pd.DataFrame(keep)


def csv_to_latex_table(csv_path="bb_flux_fraction.csv", output_path="bb_fraction_table.tex"):
    """Render the blackbody fractional-flux results as a LaTeX table."""
    df = select_rows(pd.read_csv(csv_path))

    flux_bb_decimals = decimals_for(
        np.r_[df["flux_bb_err_lower_erg_cm2_s"], df["flux_bb_err_upper_erg_cm2_s"]], FLUX_BB_NORM
    )
    flux_total_decimals = decimals_for(
        np.r_[df["flux_total_err_lower_erg_cm2_s"], df["flux_total_err_upper_erg_cm2_s"]], FLUX_TOTAL_NORM
    )
    f_bb_decimals = decimals_for(np.r_[df["f_bb_err_lower"], df["f_bb_err_upper"]], F_BB_NORM)
    f_bb_rest_decimals = decimals_for(np.r_[df["f_bb_rest_err_lower"], df["f_bb_rest_err_upper"]], F_BB_NORM)

    e_min = df["e_min_keV"].iloc[0]
    e_max = df["e_max_keV"].iloc[0]
    e_min_rest = df["e_min_keV_rest"].iloc[0]
    e_max_rest = df["e_max_keV_rest"].iloc[0]
    n_samples = int(df["n_samples"].iloc[0])
    seed = int(df["seed"].iloc[0])

    lines = [
        "% AUTO-GENERATED by codes-for-paper/bb_fraction/csv_to_latex.py",
        "% Do not edit by hand — regenerate from bb_flux_fraction.csv instead.",
        "\\begin{table*}[!ht]",
        "    \\centering",
        (
            "    \\caption{Fractional contribution of the blackbody component to the total "
            "observed energy flux, $f_\\mathrm{BB} = F_\\mathrm{BB}/F_\\mathrm{total}$, for every "
            "episode whose BEST-fitting model includes a \\bb\\ component.\n"
            f"        $f_\\mathrm{{BB}}^\\mathrm{{obs}}$ integrates both fluxes over the fixed "
            f"observer-frame band {e_min:.0f}~keV to {e_max / 1e3:.0f}~MeV, which contains more than "
            "$99.999\\%$ of the blackbody flux, and is independent of redshift and cosmology for a "
            "given episode.\n"
            f"        $f_\\mathrm{{BB}}^\\mathrm{{rest}}$ instead integrates over the fixed rest-frame "
            f"band {e_min_rest:.0f}~keV to {e_max_rest / 1e3:.0f}~MeV at the redshift given in the $z$ "
            "column, so that the comparison band is the same in the source frame for every burst rather "
            "than in the observer frame.\n"
            "        Only \\grbzeroeightzeroninesixteenC\\ has a spectroscopic redshift; for the "
            f"remaining bursts $f_\\mathrm{{BB}}^\\mathrm{{rest}}$ is quoted at a fiducial $z = "
            f"{Z_FIDUCIAL:g}$ and the full redshift dependence is shown in "
            "\\cref{fig:bbfraction-rest-vs-z}.\n"
            "        $kT$ is the fitted blackbody temperature and its $1\\sigma$ error taken directly "
            "from the joint spectral fit, not a Monte Carlo-derived quantity; the remaining columns "
            f"are the median and asymmetric $1\\sigma$ errors from ${n_samples}$ "
            f"Monte Carlo samples (seed ${seed}$) drawn from the same fit.}}"
        ),
        "    \\label{tab:bbfraction}",
        "    \\renewcommand{\\arraystretch}{1.25}",
        "    \\resizebox{\\textwidth}{!}{",
        "    \\begin{tabular}{lcccccccc}",
        "        \\toprule",
        (
            "        Model & Episode & $z$ & $kT$ & "
            "$F_\\mathrm{BB}$ & $F_\\mathrm{total}$ & "
            "$f_\\mathrm{BB}^\\mathrm{obs}$ & $f_\\mathrm{BB}^\\mathrm{rest}$ \\\\"
        ),
        (
            "         &  &  & [keV] & "
            f"\\multicolumn{{2}}{{c}}{{[${exponent_label(FLUX_BB_NORM)}$ erg\\,cm$^{{-2}}$\\,s$^{{-1}}$]}} & "
            f"[${exponent_label(F_BB_NORM)}$] & [${exponent_label(F_BB_NORM)}$] \\\\"
        ),
        "        \\midrule",
    ]

    current_grb = None
    for idx, (_, row) in enumerate(df.iterrows()):
        if row["grb_name"] != current_grb:
            if idx != 0:
                lines.append("        \\midrule")
            lines.append(f"        \\multicolumn{{8}}{{l}}{{\\textbf{{{format_grb_name(row['grb_name'])}}}}} \\\\")
            current_grb = row["grb_name"]

        z_cell = f"${row['z']:.2f}$" if row["z_source"] == "spectroscopic" else f"${row['z']:.2f}^{{\\dagger}}$"
        kt = f"${row['kt_bb_keV']:.2f} \\pm {row['kt_bb_err_keV']:.2f}$"
        f_bb_cell = format_normalised(row["f_bb"], row["f_bb_err_lower"], row["f_bb_err_upper"], F_BB_NORM,
                                       f_bb_decimals)
        f_bb_rest_cell = format_normalised(row["f_bb_rest"], row["f_bb_rest_err_lower"], row["f_bb_rest_err_upper"],
                                            F_BB_NORM, f_bb_rest_decimals)
        flux_bb_cell = format_normalised(
            row["flux_bb_erg_cm2_s"], row["flux_bb_err_lower_erg_cm2_s"],
            row["flux_bb_err_upper_erg_cm2_s"], FLUX_BB_NORM, flux_bb_decimals,
        )
        flux_total_cell = format_normalised(
            row["flux_total_erg_cm2_s"], row["flux_total_err_lower_erg_cm2_s"],
            row["flux_total_err_upper_erg_cm2_s"], FLUX_TOTAL_NORM, flux_total_decimals,
        )
        lines.append(
            f"        {format_model_name(row['model_name'])} & {row['episode']} & {z_cell} & {kt} & "
            f"{flux_bb_cell} & {flux_total_cell} & {f_bb_cell} & {f_bb_rest_cell} \\\\"
        )

    lines += [
        "        \\midrule",
        "        \\multicolumn{8}{l}{\\footnotesize $^{\\dagger}$ Assumed fiducial redshift; "
        "no spectroscopic measurement exists for this burst.} \\\\",
        "        \\bottomrule",
        "    \\end{tabular}",
        "    }",
        "\\end{table*}",
    ]

    with open(output_path, "w") as handle:
        handle.write("\n".join(lines))

    print(f"LaTeX table written to {output_path}")
    print(f"Total rows: {len(df)}")


if __name__ == "__main__":
    csv_to_latex_table()
